In [3]:
data_path = "/home/roseyu/data/tensorRNN/"
file_name = "climate.pkl"
import pickle
with open(data_path+file_name, 'rb')as fstream:
          dat = pickle.load(fstream)

In [6]:
import pandas as pd
df = pd.DataFrame(dat)
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
count,37944.000000,37944.000000,37944.000000,37944.000000,37944.000000,37944.000000,37944.000000,37944.000000,37944.000000,37944.000000,...,37944.000000,37944.000000,37944.000000,37944.000000,37944.000000,37944.000000,37944.000000,37944.000000,37944.000000,37944.000000
mean,60.710125,81.574663,77.699821,57.991013,67.056531,59.260805,66.706146,63.800337,72.637808,46.547017,...,54.974884,69.536000,62.934641,69.507985,66.431610,74.400090,63.705197,72.508144,62.765286,63.329986
std,18.654394,28.353093,32.433966,25.285533,28.558037,24.592136,22.981393,23.969106,19.985844,48.065607,...,18.252910,26.425872,29.611595,23.386288,28.952182,24.194674,27.973893,21.906151,24.973722,23.845791
min,-1.000000,-1.000000,-1.000000,-5.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-93.000000,-1.000000,-1.000000,-1.000000,-80.000000,-1.000000,-1.000000
25%,58.000000,71.000000,71.000000,44.000000,57.000000,62.000000,56.000000,52.000000,60.000000,-1.000000,...,42.000000,60.000000,63.000000,59.000000,58.000000,63.000000,50.000000,60.000000,50.000000,49.000000
50%,64.000000,86.000000,84.000000,59.000000,71.000000,67.000000,69.000000,65.000000,74.000000,59.000000,...,54.000000,73.000000,73.000000,71.000000,71.000000,77.000000,66.000000,75.000000,66.000000,64.000000
75%,70.000000,102.000000,101.000000,78.000000,88.000000,72.000000,84.000000,79.000000,88.000000,93.000000,...,70.000000,89.000000,81.000000,86.000000,87.000000,93.000000,86.000000,89.000000,82.000000,83.000000
max,107.000000,122.000000,130.000000,111.000000,117.000000,108.000000,113.000000,1943.000000,116.000000,129.000000,...,94.000000,114.000000,111.000000,115.000000,116.000000,116.000000,116.000000,117.000000,115.000000,124.000000